resolver: lts-17.1

packages:
- .
extra-deps:
- table-layout-0.9.1.0
- data-default-instances-base-0.1.0.1
- sequence-formats-1.5.2
- yaml-pretty-extras-0.0.2.2
- pandoc-citeproc-0.17.0.2
- pandoc-2.10.1
- pandoc-types-1.21
- commonmark-0.1.1.3
- commonmark-extensions-0.2.0.4
- commonmark-pandoc-0.2.0.1
- doctemplates-0.8.3
- hslua-1.1.2
- hslua-module-text-0.2.1
- skylighting-0.8.5
- skylighting-core-0.8.5
- pipes-ordered-zip-1.2.1
