resolver: lts-22.43

packages:
- .
extra-deps:
- table-layout-0.9.1.0 # not available any more in lts-22.43
- sequence-formats-1.12.1.0 # not available yet in lts-22.43
# - git: https://github.com/stschiff/sequence-formats
#   commit: 33fcbe867647a834105a7ee02081c14e2dcba575
- scotty-0.22 # not available yet in lts-22.43
allow-newer: true
